//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shoes.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class shoesEntities1 : DbContext
    {
        public shoesEntities1()
            : base("name=shoesEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<manufacturers> manufacturers { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<orders_products> orders_products { get; set; }
        public virtual DbSet<orders_statuses> orders_statuses { get; set; }
        public virtual DbSet<pick_up_points> pick_up_points { get; set; }
        public virtual DbSet<products> products { get; set; }
        public virtual DbSet<products_categories> products_categories { get; set; }
        public virtual DbSet<suppliers> suppliers { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<units> units { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<users_roles> users_roles { get; set; }
    }
}
