//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shoes.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders_products
    {
        public long order_id { get; set; }
        public string product_id { get; set; }
        public int quantity { get; set; }
    
        public virtual orders orders { get; set; }
        public virtual products products { get; set; }
    }
}
