//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shoes.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public products()
        {
            this.orders_products = new HashSet<orders_products>();
        }
    
        public string id { get; set; }
        public string title { get; set; }
        public long unit { get; set; }
        public decimal price { get; set; }
        public long supplier { get; set; }
        public long manufacturer { get; set; }
        public long category { get; set; }
        public Nullable<int> discount { get; set; }
        public Nullable<int> quantity_in_stock { get; set; }
        public string description { get; set; }
        public string photo { get; set; }
    
        public virtual manufacturers manufacturers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orders_products> orders_products { get; set; }
        public virtual products_categories products_categories { get; set; }
        public virtual suppliers suppliers { get; set; }
        public virtual units units { get; set; }

        public string Background
        {
            get
            {
                if (this.discount > 15)
                {
                    return "#2E8B57";
                }
                else if (this.quantity_in_stock == 0)
                {
                    return "Blue";
                }

                return "#fff";
            }
        }

        public string ImgPath
        {
            get
            {
                if (this.photo != null)
                {
                    var path = $"pack://application:,,,/Resources/{this.photo}";
                    return path;
                }
                else
                {
                    var path = "pack://application:,,,/Resources/picture.png";
                    return path;
                }
            }
        }
    }
}
